### ISSUE TITLE
CONTRIBUTING.md has a broken link

### ISSUE THREAD

**Issue by visto9259** [laminas/.github#48]
#### Summary

The file `CONTRIBUTING.md` has a broken link here:

> If you are working on new features or refactoring, [create a proposal](https://github.com/laminas/.github/blob/main/issues/new?labels=RFC&template=RFC.md&title=%5BRFC%5D%3A+%5BTITLE+OF+RFC%5D).

#### Expected behavior

Where is this supposed to go to?
If to create a RFC against a component, I am not sure how this can be done.
If against this repo, then link can be fixed to https://github.com/laminas/.github/issues/new?labels=RFC&template=RFC.md&title=%5BRFC%5D%3A+%5BTITLE+OF+RFC%5D

Let me know and I will submit a PR accordingly

**Comment by froschdesign** [comment]
_Good catch! 👍🏻_ 

A RFC is normally created in the repository of a component. For example, see at the issue tracker of [laminas-hydrator](https://github.com/laminas/laminas-hydrator/issues/new/choose).

Therefore, I suggest adding a new section "New Features or Refactoring" and the description that Requests for Comments (RFC) can be created in the corresponding repository via a new issue report. A detailed issue template for an RFC is stored in each repository.

**Comment by visto9259** [comment]
I stumbled on it by pure luck.

I was also wondering if some text should also explain how to submit ideas for a new component that result in a new repo. 

Unless this is explain somewhere that we can refer to, the process, AFAIK, is to submit the proposed repo to the TSC for approval. Can anyone propose a new repo to the TSC or does it have to be via a TSC member, or maintainer? Would submission be via adding an item to the TSC meeting agenda? 

Implicitly, there would have to be some discussion with the community to assess if there is an interest and get comments before submitting to the TSC in order to build the "business case" for the proposal and be able to defend it during the meeting.

**Comment by froschdesign** [comment]
> Can anyone propose a new repo to the TSC or does it have to be via a TSC member, or maintainer?

It is open – open source – so there are no restrictions.

> Would submission be via adding an item to the TSC meeting agenda?

Can be added to the [technical-steering-committee repository](https://github.com/laminas/technical-steering-committee) as an RFC and would then be discussed in a meeting.
([Some examples](https://github.com/laminas/technical-steering-committee/issues?q=is%3Aissue+is%3Aclosed) can be found in the issue tracker.)

> Implicitly, there would have to be some discussion with the community to assess if there is an interest and get comments before submitting to the TSC in order to build the "business case" for the proposal and be able to defend it during the meeting.

Can be done on the RFC or in [discussions of technical-steering-committee repository](https://github.com/laminas/technical-steering-committee/discussions) or in the forum. I think this should be clearly defined in the contribution guide.

**Comment by visto9259** [comment]
I will submit a PR with the updates and we can continue discussion during its review

**Comment by visto9259** [comment]
The same applies to Mezzio as well

**Comment by visto9259** [comment]
Darn... in the TSC issues, one cannot create a RFC issue.  The RFC template is not linked.

**Comment by visto9259** [comment]
The RFC template is not available for the TSC issues.  Someone with the rights should add it.

**Comment by froschdesign** [comment]
> The same applies to Mezzio as well

Correct!
